[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"
  
[[constraint]]
  branch = "master"
  name = "github.com/jamillosantos/macchiato"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[prune]
  go-tests = true
  unused-packages = true
